### ISSUE TITLE
Trojan-GO Build Tutorials Nginx can not start after configuring your build tutorial

### ISSUE THREAD

**Issue by goochen** [charlieethan/firewall-proxy#1]
Trojan-GO Build Tutorials Nginx can not start after configuring your build tutorial
Prompt after entering nginx -s reload command
`root@instance-1:~# nginx -s reload
nginx: [emerg] open() "/etc/nginx/sites-enabled/ai.dochenlong.top" failed (2: No such file or directory) in /etc/nginx/nginx.conf:62
`

**Comment by charlieethan** [comment]
you can try this below:     
```bash
nano /etc/nginx/sites-available/yourdomain.com  
```
Enter **Ctrl+X** to leave,and then type this command:
```bash
ln -s /etc/nginx/sites-available/yourdomain.com /etc/nginx/sites-enabled/
```
replace **yourdomain.com** to your domain     

then,try `nginx -t` ,if output like this:   
```bash
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
``` 
you can use `nginx -s reload` to restart service

**Comment by goochen** [comment]
Thank you very much, they can already run normally
and  I want to replace the 400 Bad Request page of nginx with my own 400 Bad Request page. What should I do?
Thanks！

**Comment by charlieethan** [comment]
- Step 1 : modify your own page     
```bash
vim /usr/share/nginx/html/400.html
```
Paste your own HTML code, 
- Step 2 : use `:wq` to save and then modify the config files of Nginx
```bash
vim /etc/nginx/conf.d/about.conf
```
just modify this part :
```bash
...(omission)
server {
	listen 127.0.0.1:3000;
	server_name _;
	error_page 400 /400.html;
       location = /400.html 
      {
      root /usr/share/nginx/html;
      internal;
      }
} 
```
- Step 3 : restart Nginx : 
```bash
nginx -s reload
```

**Comment by goochen** [comment]
Thank you very much!

**Comment by charlieethan** [comment]
You're welcome
